### ISSUE TITLE
Several of the machines in the /v1/adhoc/upgrades.json should be removed/changed

### ISSUE THREAD

**Issue by nkinkade** [m-lab/siteinfo#22]
@stephen-soltesz: 

* mlab2.den01: den01 is retired now, replaced by den06. mlab2.den06 is already in this list. Perhaps find an entirely new node?
* mlab3.hnd01: hnd01 is R620s and the NICs can't currently be flashed.
* mlab2.mpm01: mpm01 has never been upgraded, and still had only 3 nodes, and will likely be decommissioned in the not-distant future.

**Comment by nkinkade** [comment]
Additionally, node mlab3.lca01 should be removed. lca01 is slated to be retired at the end of this month.

**Comment by nkinkade** [comment]
Is it intentional that `mlab2.lga0t` and `mlab3.lga1t` are included in the list?

**Comment by stephen-soltesz** [comment]
* den01: okay - den06 is special. kind of like other nodes that are already updated.
* mlab3.hnd01 - can we deploy a usb stick or burn the stage1_iso image? Alternate boot media was the plan there to support old hardware. We can test on mlab{1,2}.lga1t if we need to.
* mpm01 - okay
* lca01 - okay
* lga0t & lga1t - were an accident -- i guess siteinfo doesn't identify test sites yet.

**Comment by nkinkade** [comment]
* hnd01: I wrote an email to the site host a day or two ago asking about inserting ePoxy CD or USB sticks. Haven't heard back. https://github.com/m-lab/ops-tracker/issues/735

**Comment by nkinkade** [comment]
I'm closing this because all of the upgrades have happened.
