### ISSUE TITLE
Add r1.<site>.measurement-lab.org back to the generated DNS zone file

### ISSUE THREAD

**Issue by robertodauria** [m-lab/siteinfo#28]
When we used to generate the DNS zone file via a separate repository, a `r1.<site>.measurement-lab.org` DNS entry pointing to the router's IPv4 address was created as well.

This is still needed by (at least) the DRAC configuration script to figure out what the default gateway is.

**Comment by nkinkade** [comment]
I think we can probably just modify the configure_drac.py script to calculate the gateway address using the `s1.` address instead of reintroducing the `r1.` records.
